POST http://localhost:8081/api/queue HTTP/1.1
content-type: application/json

{
    "payload": {
        "recipient": "+18777804236",
        "content": "It's go time"
    },
    "url": "http://localhost:8085/send",
    "executeAt": "2024-01-05T13:42:00Z"
}
