POST http://localhost:8081/api/queue HTTP/1.1
content-type: application/json

{
    "payload": {
        "name": "New Name",
        "count": 1
    },
    "url": "http://localhost:8080/send",
    "executeAt": "2023-12-17T19:19:10Z"
}
